<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" type="text/javascript"></script>
</head>

<!---

- https://github.com/jeremytammik/RevitLookup/pull/91
  https://github.com/jeremytammik/RevitLookup/releases/tag/2022.0.0.16
  integrated pull request #91 by @mphelt to add PartUtilsStream
  https://github.com/mphelt
  Adds PartUtilsStream that populates highlighted entries:
  a/img/revitlookup_PartUtilsStream.png
  Duplicated OriginalCategoryId shows value as f.e. OST_Walls instead of < null >.
  Duplicated GetSourceElementIds shows a 'flattened' list of elements instead of original list of LinkElementIds.
  Duplicated GetSourceElementOriginalCategoryIds uses EnumerableAsString to show value as f.e. 'OST_Walls, OST_Walls'.

- C# templates for Revit
  Роман Карпович <nice3point@gmail.com>
  Hi Jeremy, I made some really cool templates for creating revit plugins. With a build system, creating installers and bundles for the Autodesk Store. Ready-made files for AzureDevOps, GitHubActions have been written. A minimum of steps for starting and routine work, all GUIDs are generated by themselves when creating a project. Added the ability to merge several DLLs into one, just specify the names of the merged files. For Debug configurations, all files are copied to the addons folder by themselves. It is also possible to add unique configurations, for example, a configuration for AdskStore, where you can check whether a plugin is purchased or not, in the second case, display an informational message and redirect to a page in the store. You can test them here https://github.com/Nice3point/RevitTemplates and share them on your blog. Video with an example in the attached files.
  FirstSteps.mp4 -- https://drive.google.com/file/d/1Pm0tygJNRcXP_8O8XCsk2C5Jt3FQFCym/view
  StoreVersion.mp4 -- https://drive.google.com/file/d/1bPveyMoGi0U9MVTT0UxWVPK7gXb2amJu/view
  https://github.com/Nice3point/RevitTemplates

- C# and IronPython Hosting for Revit addins
  https://forums.autodesk.com/t5/revit-api-forum/c-and-ironpython-hosting-for-revit-addins/m-p/10629723
  
- CPython and Python 3
  PyRevit and Revit 2022 w/ Dynamo
  https://forums.autodesk.com/t5/revit-api-forum/pyrevit-and-revit-2022-w-dynamo/m-p/10638367

twitter:

add #thebuildingcoder

 the #RevitAPI #DynamoBim @AutodeskForge @AutodeskRevit #bim #ForgeDevCon 

&ndash; 
...

linkedin:

#bim #DynamoBim #ForgeDevCon #Revit #API #IFC #SDK #AI #VisualStudio #Autodesk #AEC #adsk

the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread

<center>
<img src="img/" alt="" title="" width="600"/>
<p style="font-size: 80%; font-style:italic"></p>
</center>

**Question:** 

**Answer:**

**Response:**  

Many thanks to  for this very helpful explanation!

<pre class="code">
</pre>

-->

### Snooping Parts, Python Topics and C&#35; Templates




####<a name="2"></a> RevitLokup Handles PartUtils

RevitLokup now displays `PartUtils` information.

[mphelt](https://github.com/mphelt) submitted
[pull request #91 to add `PartUtilsStream`](https://github.com/jeremytammik/RevitLookup/pull/91),
integrated in [RevitLookup release 2022.0.0.16](https://github.com/jeremytammik/RevitLookup/releases/tag/2022.0.0.16).

The new `PartUtils` stream also populates the following highlighted entries:

<center>
<img src="img/revitlookup_PartUtilsStream.png" alt="Snoop PartUtils" title="Snoop PartUtils" width="354"/> <!-- 354 -->
</center>

- Duplicated `OriginalCategoryId` shows value as f.e. `OST_Walls` instead of `&lt;null&gt;`
- Duplicated `GetSourceElementIds` shows a flattened list of elements instead of original list of `LinkElementIds`
- Duplicated `GetSourceElementOriginalCategoryIds` uses `EnumerableAsString` to show value as f.e. 'OST_Walls, OST_Walls'

Many thanks to [mphelt](https://github.com/mphelt) for the importasnt enhancement!


####<a name="3"></a> Nice3point Revit Add-In C&#35; Template 

We mentioned several alternatives to
my very simple [Visual Studio Revit add-in wizard](https://github.com/jeremytammik/VisualStudioRevitAddinWizard) in
the past.

I just added a list of them to the GitHub repo readme and
the corresponding [topic group](https://thebuildingcoder.typepad.com/blog/about-the-author.html#5.20).

Roman Karpov, aka Роман Карпович, now shares another one, saying:

> I made some really cool templates for creating Revit plugins.
They include a build system, creating installers, creating bundles for the Autodesk AppStore, ready-made files for AzureDevOps, and GitHubActions.
They require a minimum of steps for starting and routine work.
All GUIDs are automatically generated when creating a project.
Added the ability to merge several DLLs into one; just specify the names of the merged files.
For Debug configurations, all files are copied to the add-ins folder by themselves.
It is also possible to add unique configurations; for example, a configuration for AdskStore, where you can check whether a plugin has been purchased or not; if not, display an informational message and redirect to a page in the store.

> You can test them at [Nice3point/RevitTemplates](https://github.com/Nice3point/RevitTemplates).

> Check out the example videos:

- [FirstSteps.mp4](https://drive.google.com/file/d/1Pm0tygJNRcXP_8O8XCsk2C5Jt3FQFCym/view)
- [StoreVersion.mp4](https://drive.google.com/file/d/1bPveyMoGi0U9MVTT0UxWVPK7gXb2amJu/view)
- [Nice3point/RevitTemplates](https://github.com/Nice3point/RevitTemplates)

Thank you very much for sharing these, Роман!


####<a name="4"></a> IronPython Hosting in C&#35; Add-In

Daniel Gerčák shares a solution implementing his
own [IronPython](https://ironpython.net) hosting in a Revit add-in in
the [Revit API discussion forum](http://forums.autodesk.com/t5/revit-api-forum/bd-p/160) thread
on [C&#35; and IronPython hosting for Revit addins](https://forums.autodesk.com/t5/revit-api-forum/c-and-ironpython-hosting-for-revit-addins/m-p/10629723):


**Question:** I try to run IronPython scripts via IronPython.Hosting in C#, inspired by Nick Cosentino's
article [Python, Visual Studio, and C&#35;, so sweet](https://www.codeproject.com/Articles/657698/Python-Visual-Studio-and-Csharp-So-Sweet).

The purpose of such effort is to create easy distributable and accessible addins in our company which are developed by a small group of non IT experts on the IronPython platform due to it's flexibility and lower demandings for coding skills.
Yes, I've heard about RevitPythonShell, but this is not exactly what would make sufficient result.

I was able to run classes using references to `RevitAPI` and `RevitAPIUI` but receive empty objects trying to use `RevitServices`:

<pre class="prettyprint">
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument
</pre>

I wonder if my intention to run such scripts is useless effort due to some restrictions in source code or is there some way to deal with this issue.

Here is a piece of code for better overview of what I am trying to achieve,
[totalSelectedVolume.zip](zip/dg_totalSelectedVolume.zip),
containing totalSelectedVolumeCommand.cs and totalSelectedVolume.py.
The former implements an external command and executes the latter via the `IronPython.Hosting` `ExecuteFile` method, performing the actual computation.

**Answer:** You can take a look at the open source implementations
of [RevitPythonShell](https://github.com/architecture-building-systems/revitpythonshell)
and [pyRevit](https://github.com/eirannejad/pyRevit) to
discover how they have addressed this same issue.

**Response:** I did a little research and I was succesful.

The point was to create a new variable within the IronPython engine and assign the `commandData.Application` object to it so that you can access it from the Python environment.
I named it the same way as it is in RPS, `__revit__`, in order to keep compatibility with scripts developed for RPS.
Since I've tested it only by using simple Python code, I don't guarantee its functionality with more complex scripts.
Additional settings might be required.

The execute function looks like this.

<pre class="code"> 

public Result Execute(
ExternalCommandData commandData,
ref string message,
ElementSet elements)
{
UIApplication _revit = commandData.Application;
UIDocument uidoc = _revit.ActiveUIDocument;
Application app = _revit.Application;
Document doc = uidoc.Document;

var flags = new Dictionary<string, object>() { { "Frames", true }, { "FullFrames", true } };
var py = IronPython.Hosting.Python.CreateEngine(flags);
var scope = IronPython.Hosting.Python.CreateModule(py, "__main__");
scope.SetVariable("__commandData__", commandData);

// add special variable: __revit__ to be globally visible everywhere:
var builtin = IronPython.Hosting.Python.GetBuiltinModule(py);
builtin.SetVariable("__revit__", _revit);
py.Runtime.LoadAssembly(typeof(Autodesk.Revit.DB.Document).Assembly);
py.Runtime.LoadAssembly(typeof(Autodesk.Revit.UI.TaskDialog).Assembly);

try
{
py.ExecuteFile("totalSelectedVolume.py");
}
catch (Exception ex)
{
TaskDialog myDialog = new TaskDialog("IronPython Error");
myDialog.MainInstruction = "Couldn't execute IronPython script totalSelectedVolume.py: ";
myDialog.ExpandedContent = ex.Message;
myDialog.Show();
}

return Result.Succeeded;
</pre>

Here is [IronPython_engine.zip](zip/dg_IronPython_engine.zip) containing a complete testing project.

Many thanks to Daniel for his research and useful solution!

####<a name="5"></a> Python 3, CPython, pyRevit and Dynamo

Continuing with POython related issues, here is a quick update on upcoming releases of pyRevit and Dynamo and their support for Python 3:


CPython and Python 3
PyRevit and Revit 2022 w/ Dynamo
https://forums.autodesk.com/t5/revit-api-forum/pyrevit-and-revit-2022-w-dynamo/m-p/10638367



<pre class="code">

</pre>



**Answer:** 

