#!/bin/bash

#curl -X 'GET' -H "Authorization: Bearer $FORGE_ACCESS_TOKEN" -H 'If-Modified-Since: SAT, 21 May 2016 02:40:25 GMT' -v 'https://developer.api.autodesk.com/modelderivative/v2/designdata/formats'

curl -X 'GET' -H "Authorization: Bearer $FORGE_ACCESS_TOKEN" -v 'https://developer.api.autodesk.com/modelderivative/v2/designdata/formats'
